[tool.uv.workspace]
members = ["bifrost", "broker", "engine", "rollouts"]

[project]
name = "llm-workbench"
version = "0.1.0"
description = "Complete toolkit for GPU-accelerated machine learning workflows"
requires-python = ">=3.10"
# Default: Full GPU stack for remote deployment
dependencies = [
    "rollouts",
    "broker",
    "bifrost",
    "engine"
]

[project.optional-dependencies]
# Lightweight local development - no ML dependencies
local = [
    "rollouts",
    "broker", 
    "bifrost"
]

# Interpretability features - includes engine with nnsight
interp = [
    "rollouts",
    "broker", 
    "bifrost",
    "engine[interp]"
]

[tool.uv.sources]
rollouts = { workspace = true }
broker = { workspace = true }
bifrost = { workspace = true }
engine = { workspace = true }

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]
include = []  # Meta-package - no code in root
