[project]
name = "shared"
version = "0.1.0"
description = "Shared utilities for llm-workbench"
requires-python = ">=3.10"
dependencies = []

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"